
spring:
  output:
    ansi:
      enabled: always # 控制台彩色输出
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      maximum-pool-size: 5 # 连接池最大连接数量
      minimumIdle: 5 # 最小空闲连接数
      idleTimeout: 600000 # 连接空闲时间
      connectionTimeout: 30000 # 连接超时时间
      maxLifetime: 1800000 # 连接最大生存时间
server:
  port: 8081
management:
  security:
    enabled: false